services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ERPLY_API_KEY=${ERPLY_API_KEY}
      - ERPLY_CLIENT_CODE=${ERPLY_CLIENT_CODE}
      - DB_URI=${MONGO_URI}
    depends_on:
      - mongo
    volumes:
      - .env:/app/.env

    # volumes:
    #   - .:/app
    restart: unless-stopped

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: