services:
  api:
    build: 
      context: ..
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    ports:
      - ${APP_PORT}:8080
    environment:
      - ERPLY_USER_PASS=${ERPLY_USER_PASS}
      - ERPLY_USER_NAME=${ERPLY_USER_NAME}
      - ERPLY_CLIENT_CODE=${ERPLY_CLIENT_CODE}
      - REDIS_ADDR=${REDIS_ADDR}
      - API_KEY=${API_KEY}
    depends_on:
      - redis

    restart: unless-stopped

  redis:
      image: redis:latest
      ports:
        - "6379:6379"
      restart: unless-stopped
